
matrix = {
    "SUPERUSER": [
        # Identity Management
        "STUDENT_CREATE", "STUDENT_READ", "STUDENT_UPDATE", "STUDENT_DELETE",
        "STUDENT_ARCHIVE", "STUDENT_RESTORE",

        "STAFF_CREATE", "STAFF_READ", "STAFF_UPDATE", "STAFF_DELETE",
        "STAFF_ARCHIVE", "STAFF_RESTORE",

        "EDUCATOR_CREATE", "EDUCATOR_READ", "EDUCATOR_UPDATE", "EDUCATOR_DELETE",
        "EDUCATOR_ARCHIVE", "EDUCATOR_RESTORE",

        "GUARDIAN_CREATE", "GUARDIAN_READ", "GUARDIAN_UPDATE", "GUARDIAN_DELETE",
        "GUARDIAN_ARCHIVE", "GUARDIAN_RESTORE",

        # Staff Management
        "STAFF_DEPARTMENT_CREATE", "STAFF_DEPARTMENT_READ", "STAFF_DEPARTMENT_UPDATE", "STAFF_DEPARTMENT_DELETE",
        "STAFF_DEPARTMENT_ARCHIVE", "STAFF_DEPARTMENT_RESTORE",

        "STAFF_JOB_TITLE_CREATE", "STAFF_JOB_TITLE_READ", "STAFF_JOB_TITLE_UPDATE", "STAFF_JOB_TITLE_DELETE",
        "STAFF_JOB_TITLE_ARCHIVE", "STAFF_JOB_TITLE_RESTORE",

        "EDUCATOR_QUALIFICATION_CREATE", "EDUCATOR_QUALIFICATION_READ", "EDUCATOR_QUALIFICATION_UPDATE", "EDUCATOR_QUALIFICATION_DELETE",
        "EDUCATOR_QUALIFICATION_ARCHIVE", "EDUCATOR_QUALIFICATION_RESTORE",

        # Academic Structure
        "CLASSES_CREATE", "CLASSES_READ", "CLASSES_UPDATE", "CLASSES_DELETE",
        "CLASSES_ARCHIVE", "CLASSES_RESTORE",

        "DEPARTMENT_CREATE", "DEPARTMENT_READ", "DEPARTMENT_UPDATE", "DEPARTMENT_DELETE",
        "DEPARTMENT_ARCHIVE", "DEPARTMENT_RESTORE",

        "ACADEMIC_LEVEL_CREATE", "ACADEMIC_LEVEL_READ", "ACADEMIC_LEVEL_UPDATE", "ACADEMIC_LEVEL_DELETE",
        "ACADEMIC_LEVEL_ARCHIVE", "ACADEMIC_LEVEL_RESTORE",

        # Curriculum
        "SUBJECT_CREATE", "SUBJECT_READ", "SUBJECT_UPDATE", "SUBJECT_DELETE",
        "SUBJECT_ARCHIVE", "SUBJECT_RESTORE",
        "ACADEMIC_LEVEL_SUBJECT_CREATE", "ACADEMIC_LEVEL_SUBJECT_READ", "ACADEMIC_LEVEL_SUBJECT_UPDATE", "ACADEMIC_LEVEL_SUBJECT_DELETE",
        "ACADEMIC_LEVEL_SUBJECT_ARCHIVE", "ACADEMIC_LEVEL_SUBJECT_RESTORE",

        "STUDENT_SUBJECT_CREATE", "STUDENT_SUBJECT_READ", "STUDENT_SUBJECT_DELETE",
        "STUDENT_SUBJECT_ARCHIVE", "STUDENT_SUBJECT_RESTORE",

        "SUBJECT_EDUCATOR_CREATE", "SUBJECT_EDUCATOR_READ", "SUBJECT_EDUCATOR_DELETE",
        "SUBJECT_EDUCATOR_ARCHIVE", "SUBJECT_EDUCATOR_RESTORE",

        # Assessment
        "GRADE_CREATE", "GRADE_READ", "GRADE_UPDATE", "GRADE_DELETE",
        "GRADE_ARCHIVE", "GRADE_RESTORE",

        "TOTAL_GRADE_CREATE", "TOTAL_GRADE_READ", "TOTAL_GRADE_UPDATE", "TOTAL_GRADE_DELETE",
        "TOTAL_GRADE_ARCHIVE", "TOTAL_GRADE_RESTORE",

        # Documents & Awards
        "DOCUMENT_CREATE", "DOCUMENT_READ", "DOCUMENT_UPDATE", "DOCUMENT_DELETE",
        "DOCUMENT_ARCHIVE", "DOCUMENT_RESTORE",

        "AWARD_CREATE", "AWARD_READ", "AWARD_UPDATE", "AWARD_DELETE",
        "AWARD_ARCHIVE", "AWARD_RESTORE",

        # Progression
        "TRANSFER_CREATE", "TRANSFER_READ", "TRANSFER_UPDATE", "TRANSFER_DELETE",
        "TRANSFER_ARCHIVE", "TRANSFER_RESTORE", "TRANSFER_APPROVE", "TRANSFER_REJECT",

        "PROMOTION_CREATE", "PROMOTION_READ", "PROMOTION_UPDATE", "PROMOTION_DELETE",
        "PROMOTION_ARCHIVE", "PROMOTION_RESTORE", "PROMOTION_APPROVE", "PROMOTION_REJECT",

        "REPETITION_CREATE", "REPETITION_READ", "REPETITION_UPDATE", "REPETITION_DELETE",
        "REPETITION_ARCHIVE", "REPETITION_RESTORE", "REPETITION_APPROVE", "REPETITION_REJECT",

        # RBAC
        "ROLE_CREATE", "ROLE_READ", "ROLE_UPDATE", "ROLE_DELETE",
        
        "ROLE_PERMISSION_CREATE", "ROLE_PERMISSION_READ", "ROLE_PERMISSION_UPDATE", "ROLE_PERMISSION_DELETE",
                
        "ROLE_CHANGE_CREATE", "ROLE_CHANGE_READ", "ROLE_CHANGE_UPDATE", "ROLE_CHANGE_DELETE",
        "ROLE_CHANGE_ARCHIVE", "ROLE_CHANGE_RESTORE",
        

        #Audit
        "AUDIT_READ"
    ],

    "STUDENT": [
        # Identity Management - Own records only
        "STUDENT_READ", "STUDENT_UPDATE",
        "STAFF_READ",
        "EDUCATOR_READ",
        "GUARDIAN_READ",

        # Academic Structure - Related to their studies
        "CLASSES_READ",
        "DEPARTMENT_READ",
        "ACADEMIC_LEVEL_READ",

        # Curriculum - Their subjects
        "SUBJECT_READ",
        "ACADEMIC_LEVEL_SUBJECT_READ",
        "STUDENT_SUBJECT_READ",
        "SUBJECT_EDUCATOR_READ",

        # Assessment - Own grades
        "GRADE_READ",
        "TOTAL_GRADE_READ",

        # Documents & Awards - Own records
        "DOCUMENT_READ",
        "AWARD_READ",

        # Progression
        "TRANSFER_CREATE",
        "PROMOTION_READ",
        "REPETITION_READ",
    ],

    "GUARDIAN": [
        # Identity Management - Ward records only
        "STUDENT_READ",
        "STAFF_READ",
        "EDUCATOR_READ", #on subject allocations
        "GUARDIAN_READ", "GUARDIAN_UPDATE",

        # Academic Structure - Ward's academic info
        "CLASSES_READ",
        "DEPARTMENT_READ",
        "ACADEMIC_LEVEL_READ",

        # Curriculum - Ward's subjects
        "SUBJECT_READ",
        "ACADEMIC_LEVEL_SUBJECT_READ",
        "STUDENT_SUBJECT_READ",
        "SUBJECT_EDUCATOR_READ",

        # Assessment - Ward's grades
        "GRADE_READ",
        "TOTAL_GRADE_READ",

        # Documents & Awards - Ward's records
        "DOCUMENT_READ",
        "AWARD_READ",

        # Progression
        "TRANSFER_READ",
        "PROMOTION_READ",
        "REPETITION_READ",
    ],

    "INACTIVE":[
        "STAFF_READ" #Oen records
    ]
}

