from .users.guardian import GuardianFactory
from .users.staff import StaffFactory
from .users.student import StudentFactory
from .student_organization.academic_level import AcademicLevelFactory
from .student_organization.classes import ClassFactory
from .student_organization.department import StudentDepartmentFactory
from .staff_organization.qualification import QualificationFactory
from .staff_organization.department import StaffDepartmentFactory
from .staff_organization.staff_role import StaffRoleFactory
