[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kademia"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"


dependencies = []

[tool.setuptools]
packages = ["app", "logs", "auth_logs"]
include-package-data = true
