"""Changed column archive_reason to an Enum

Revision ID: 14fb97cd8d7c
Revises: 0f8f305651f3
Create Date: 2025-02-06 00:46:38.016106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '14fb97cd8d7c'
down_revision: Union[str, None] = '0f8f305651f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

archive_reason = postgresql.ENUM('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE',
                                 name='archivereason')



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    archive_reason.create(op.get_bind())

    op.alter_column('classes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute("ALTER TABLE classes ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")



    op.alter_column('departments', 'is_archived',
               existing_type=sa.BOOLEAN(),nullable=False)
    op.execute("ALTER TABLE departments ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")
    
    op.alter_column('educator_qualifications', 'is_archived',
               existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("ALTER TABLE educator_qualifications ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.execute("ALTER TABLE grades ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")
    
    op.alter_column('parents', 'is_archived',
               existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("ALTER TABLE parents ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.execute("ALTER TABLE repetitions ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")
    
    op.alter_column('staff', 'is_archived',existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("ALTER TABLE staff ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")
    
    op.alter_column('staff_departments', 'is_archived',
                    existing_type=sa.BOOLEAN(),nullable=False)
    op.execute("ALTER TABLE staff_departments ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.alter_column('staff_roles', 'is_archived',
               existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("ALTER TABLE staff_roles ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.alter_column('student_documents', 'is_archived',
               existing_type=sa.BOOLEAN(),nullable=False)
    op.execute("ALTER TABLE student_documents ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.execute("ALTER TABLE student_subjects ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.execute("ALTER TABLE student_transfers ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.alter_column('students', 'is_archived',
               existing_type=sa.BOOLEAN(),nullable=False)
    op.execute("ALTER TABLE students ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.alter_column('subjects', 'is_archived',
               existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("ALTER TABLE subjects ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")

    op.execute("ALTER TABLE total_grades ALTER COLUMN archive_reason TYPE archivereason USING archive_reason::text::archivereason")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    archive_reason.drop(op.get_bind())

    op.alter_column('total_grades', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('subjects', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('subjects', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('students', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('students', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('student_transfers', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('student_subjects', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('student_documents', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('student_documents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff_roles', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('staff_roles', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff_departments', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('staff_departments', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('staff', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('repetitions', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('parents', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('parents', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('grades', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('educator_qualifications', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('educator_qualifications', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('departments', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('departments', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('classes', 'archive_reason',
               existing_type=sa.Enum('ERROR', 'GRADUATED', 'TRANSFERRED', 'WITHDRAWN', 'ADMINISTRATIVE', name='archivereason', nullable=True),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('classes', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
