"""dropped column is_verified from ProfileBase

Revision ID: 21230b35b6a5
Revises: 381fd576b5be
Create Date: 2025-02-01 06:32:03.308850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '21230b35b6a5'
down_revision: Union[str, None] = '381fd576b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'is_verified')
    op.drop_column('staff', 'is_verified')
    op.drop_column('students', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('staff', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('parents', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
