"""Renamed Enum Subjectdepartment type

Revision ID: 2cebe4260b15
Revises: 45b1fc9ade6c
Create Date: 2025-01-20 18:26:47.545625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cebe4260b15'
down_revision: Union[str, None] = '45b1fc9ade6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE TYPE subjectgroup AS ENUM ('SCIENCE', 'HUMANITIES', 'BUSINESS', 'GENERAL');""")

    op.add_column('subjects',sa.Column( 'group',  sa.Enum('SCIENCE', 'HUMANITIES', 'BUSINESS', 'GENERAL',
                                                          name='subjectgroup'),nullable=True))
    op.drop_column('subjects', 'department_type')

    op.execute("DROP TYPE subjectdepartmenttype;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('department_type', postgresql.ENUM('SCIENCE', 'HUMANITIES', 'BUSINESS', 'General', name='subjectdepartmenttype'), autoincrement=False, nullable=False))
    op.drop_column('subjects', 'group')
    # ### end Alembic commands ###
