"""renamed is_compulsory to is_elective

Revision ID: 2f264d4baf72
Revises: 2cebe4260b15
Create Date: 2025-01-20 18:49:40.041231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '2f264d4baf72'
down_revision: Union[str, None] = '2cebe4260b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('is_elective', sa.Boolean(), nullable=False))
    op.drop_column('subjects', 'is_compulsory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('is_compulsory', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('subjects', 'is_elective')
    # ### end Alembic commands ###
