"""removed has_active_wards column from parents table

Revision ID: 35a7e955b136
Revises: be06f1392b7e
Create Date: 2025-02-12 11:14:13.626164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '35a7e955b136'
down_revision: Union[str, None] = 'be06f1392b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'has_active_wards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('has_active_wards', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
