"""Changed FK in AccessLevelChanges to staff.id

Revision ID: 37685a87540d
Revises: df2fb13209bb
Create Date: 2025-01-24 00:07:28.347463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '37685a87540d'
down_revision: Union[str, None] = 'df2fb13209bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_level_changes', sa.Column('staff_id', sa.UUID(), nullable=False))
    op.drop_constraint('access_level_changes_user_id_fkey', 'access_level_changes', type_='foreignkey')
    op.create_foreign_key(None, 'access_level_changes', 'staff', ['staff_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_level_changes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_level_changes', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'access_level_changes', type_='foreignkey')
    op.create_foreign_key('access_level_changes_user_id_fkey', 'access_level_changes', 'staff', ['user_id'], ['id'])
    op.drop_column('access_level_changes', 'staff_id')
    # ### end Alembic commands ###
