"""defined relationship between student and documents on student documents table

Revision ID: 50449214c8fa
Revises: 5942ba7a9c16
Create Date: 2025-01-22 04:09:46.336012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '50449214c8fa'
down_revision: Union[str, None] = '5942ba7a9c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_documents', 'students', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_documents', type_='foreignkey')
    # ### end Alembic commands ###
