"""defined relationship between student and documents on student documents table

Revision ID: 5942ba7a9c16
Revises: e189780b2e5b
Create Date: 2025-01-22 04:02:16.597796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '5942ba7a9c16'
down_revision: Union[str, None] = 'e189780b2e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
