"""Added EducatorQualifications table, added Column date_of_birth to Students

Revision ID: 81ef10f324cd
Revises: 37685a87540d
Create Date: 2025-01-26 22:42:10.788082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '81ef10f324cd'
down_revision: Union[str, None] = '37685a87540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educator_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('educator_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_soft_deleted', sa.Boolean(), nullable=False),
    sa.Column('soft_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=500), nullable=True),
    sa.Column('soft_deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['educator_id'], ['educator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_modified_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['soft_deleted_by'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'date_of_birth')
    op.drop_table('educator_qualifications')
    # ### end Alembic commands ###
