"""Renamed user_id column in ProfieBase to id and removed the redundant id columns in inherited tables

Revision ID: 939314069596
Revises: 81ef10f324cd
Create Date: 2025-01-28 06:14:57.817048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '939314069596'
down_revision: Union[str, None] = '81ef10f324cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'user_id')
    op.drop_column('staff', 'user_id')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('staff', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('parents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
