"""removed from_department from StudentTransfers table and used from_department_id

Revision ID: abd1c0ce2a73
Revises: 50449214c8fa
Create Date: 2025-01-22 04:21:56.139798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abd1c0ce2a73'
down_revision: Union[str, None] = '50449214c8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_transfers', sa.Column('from_department_id', sa.UUID(), nullable=False))
    op.add_column('student_transfers', sa.Column('to_department_id', sa.UUID(), nullable=False))
    op.drop_index('idx_from_department', table_name='student_transfers')
    op.drop_index('idx_to_department', table_name='student_transfers')
    op.create_index('idx_from_department_id', 'student_transfers', ['from_department_id'], unique=False)
    op.create_index('idx_to_department_id', 'student_transfers', ['to_department_id'], unique=False)
    op.create_foreign_key(None, 'student_transfers', 'departments', ['to_department_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'student_transfers', 'departments', ['from_department_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('student_transfers', 'to_department')
    op.drop_column('student_transfers', 'from_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_transfers', sa.Column('from_department', postgresql.ENUM('SCIENCE', 'HUMANITIES', 'BUSINESS', name='departmentname'), autoincrement=False, nullable=False))
    op.add_column('student_transfers', sa.Column('to_department', postgresql.ENUM('SCIENCE', 'HUMANITIES', 'BUSINESS', name='departmentname'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_transfers', type_='foreignkey')
    op.drop_constraint(None, 'student_transfers', type_='foreignkey')
    op.drop_index('idx_to_department_id', table_name='student_transfers')
    op.drop_index('idx_from_department_id', table_name='student_transfers')
    op.create_index('idx_to_department', 'student_transfers', ['to_department'], unique=False)
    op.create_index('idx_from_department', 'student_transfers', ['from_department'], unique=False)
    op.drop_column('student_transfers', 'to_department_id')
    op.drop_column('student_transfers', 'from_department_id')
    # ### end Alembic commands ###
