"""see circular fks

Revision ID: cf89c196b864
Revises: 39dc638b0954
Create Date: 2025-01-22 00:47:39.060883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = 'cf89c196b864'
down_revision: Union[str, None] = '39dc638b0954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
