"""Modified Gender, UserType and Stafftype

Revision ID: e189780b2e5b
Revises: 0785e24b9e21
Create Date: 2025-01-22 03:16:42.409665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = 'e189780b2e5b'
down_revision: Union[str, None] = '0785e24b9e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE usertype RENAME TO old_usertype")
    op.execute("CREATE TYPE usertype AS ENUM ('Student', 'Parent', 'Staff', 'System')")
    op.execute("ALTER TABLE users ALTER COLUMN user_type TYPE usertype USING user_type::text::usertype")
    op.execute("DROP TYPE old_usertype")

    op.execute("ALTER TYPE gender RENAME TO old_gender")
    op.execute("CREATE TYPE gender AS ENUM ('M', 'F', 'S')")
    op.execute("ALTER TABLE students ALTER COLUMN gender TYPE gender USING gender::text::gender")
    op.execute("ALTER TABLE staff ALTER COLUMN gender TYPE gender USING gender::text::gender")
    op.execute("ALTER TABLE parents ALTER COLUMN gender TYPE gender USING gender::text::gender")
    op.execute("DROP TYPE old_gender")

    op.execute("ALTER TYPE stafftype RENAME TO old_stafftype")
    op.execute("CREATE TYPE stafftype AS ENUM ('Educator', 'Admin', 'Support', 'System')")
    op.execute("ALTER TABLE staff ALTER COLUMN staff_type TYPE stafftype USING staff_type::text::stafftype")
    op.execute("DROP TYPE old_stafftype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
