"""Dropped Admin table and included system, modified staff type enum, fixed usertype and stafftype enum definition in users ans staff table

Revision ID: f27745be0346
Revises: abd1c0ce2a73
Create Date: 2025-01-22 05:54:05.740623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from V2.app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = 'f27745be0346'
down_revision: Union[str, None] = 'abd1c0ce2a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE stafftype RENAME TO old_stafftype")
    op.execute("CREATE TYPE stafftype AS ENUM ('Educator', 'Operations', 'Support', 'System')")
    op.execute("ALTER TABLE staff ALTER COLUMN staff_type TYPE stafftype USING staff_type::text::stafftype")
    op.execute("DROP TYPE old_stafftype")
    op.create_table('system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], name='admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_pkey')
    )
    op.drop_table('system')
    # ### end Alembic commands ###
