"""Removed Management and commercials table, included ops

Revision ID: 9131957c66d6
Revises: ec89d7e19bf8
Create Date: 2025-01-18 07:08:46.908393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.models.common_imports import Base


# revision identifiers, used by Alembic.
revision: str = '9131957c66d6'
down_revision: Union[str, None] = 'ec89d7e19bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('management')
    op.drop_table('commercial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], name='commercial_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commercial_pkey')
    )
    op.create_table('management',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['staff.id'], name='management_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='management_pkey')
    )
    op.drop_table('operations')
    # ### end Alembic commands ###
